### ISSUE TITLE
Can't create resources

### ISSUE THREAD

**Issue by unixequinix** [a10networks/terraform-provider-vthunder#2]
Hi,

We are trying to create virtualservers in our a10. Right now we are using a python script that talks with the API. Because of the complexity of the code, and for maintenance, we wanted to "migrate" that process to terraform.

But we couldn't manage to create a simple server with the provider.

Taking a look on the provider code we think there could be 2 problems here:

1. In the auth section, we think there is an error taking the value of the uri. You take the server value but not the uri of the API, or maybe, if the value is implicit, we have an incompatibility with the version.

2. With out python script, we needed to force "context=ssl._create_unverified_context()", and maybe that an option not declared in the providers code.

Please, let us know if you need more info about our case.

Thank you.

Regards.

**Comment by smita-a10** [comment]
Hi,

Thanks for reaching out. 
Can you send us the Terraform (.tf) file used to create the simple server?

Thank you.

**Comment by devendra-bhatt-a10** [comment]
Due to lack of response and recent changes in provider code please try to recreate the issue and let us know we will reopen this ticket. Till then closing it.
